#定义服务应用名称
spring:
  application:
    name: trim-space
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    mvc:
      throw-exception-if-no-handler-found: true
    resources:
      add-mappings: true

server:
  port: 80
